import os
import subprocess
import sys
import shutil

def check_pdflatex():
    """Check if pdflatex is available in the system path."""
    if shutil.which("pdflatex") is None:
        # Check common Windows install locations
        common_paths = [
            os.path.expanduser(r"~\AppData\Local\Programs\MiKTeX\miktex\bin\x64"),
            r"C:\Program Files\MiKTeX\miktex\bin\x64"
        ]
        
        for path in common_paths:
            if os.path.exists(os.path.join(path, "pdflatex.exe")):
                print(f"Found pdflatex at {path}. Adding to PATH.")
                os.environ["PATH"] += os.pathsep + path
                return True
                
        print("Error: 'pdflatex' not found. Please install a LaTeX distribution (e.g., TeX Live, MiKTeX).")
        return False
    return True

def generate_figures():
    """Run the figure generation script."""
    print("Generating figures...")
    try:
        # Run from project root
        result = subprocess.run([sys.executable, "lab/generate_figures.py"], check=True, capture_output=True, text=True)
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print("Error generating figures:")
        print(e.stderr)
        sys.exit(1)

def compile_paper(paper_path):
    """Compile a single LaTeX paper."""
    paper_dir = os.path.dirname(paper_path)
    paper_file = os.path.basename(paper_path)
    
    print(f"Compiling {paper_file}...")
    
    try:
        # Run pdflatex inside the papers directory
        # -interaction=nonstopmode prevents hanging on errors
        subprocess.run(
            ["pdflatex", "-interaction=nonstopmode", paper_file], 
            cwd=paper_dir, 
            check=True, 
            capture_output=True
        )
        print(f"Successfully compiled {paper_file}")
    except subprocess.CalledProcessError:
        print(f"Failed to compile {paper_file}. Check log file for details.")

def cleanup(papers_dir):
    """Remove auxiliary files generated by pdflatex."""
    print("Cleaning up auxiliary files...")
    extensions = [".aux", ".log", ".out"]
    for filename in os.listdir(papers_dir):
        if any(filename.endswith(ext) for ext in extensions):
            os.remove(os.path.join(papers_dir, filename))
            print(f"Removed {filename}")

def main():
    # Ensure we are in the project root
    if not os.path.exists("lab/generate_figures.py"):
        print("Error: Please run this script from the project root directory.")
        sys.exit(1)

    # 1. Generate Figures
    generate_figures()

    # 2. Check for LaTeX
    if not check_pdflatex():
        print("Skipping PDF compilation.")
        return

    # 3. Compile Papers
    papers_dir = "papers"
    if not os.path.exists(papers_dir):
        print(f"Error: {papers_dir} directory not found.")
        sys.exit(1)

    for filename in os.listdir(papers_dir):
        if filename.endswith(".tex"):
            compile_paper(os.path.join(papers_dir, filename))

    # 4. Cleanup
    cleanup(papers_dir)

if __name__ == "__main__":
    main()
