import os
import subprocess
import sys
import shutil

def find_pdflatex():
    """Find pdflatex and return its full path, or None if not found."""
    # First check if it's in PATH
    pdflatex_path = shutil.which("pdflatex")
    if pdflatex_path:
        return pdflatex_path

    # Detect if running in WSL
    is_wsl = os.path.exists("/mnt/c")

    if is_wsl:
        # WSL paths to Windows MiKTeX
        username = os.environ.get("USER", "")
        common_paths = [
            f"/mnt/c/Users/{username}/AppData/Local/Programs/MiKTeX/miktex/bin/x64",
            "/mnt/c/Program Files/MiKTeX/miktex/bin/x64"
        ]
        exe_name = "pdflatex.exe"
    else:
        # Native Windows paths
        common_paths = [
            os.path.expanduser(r"~\AppData\Local\Programs\MiKTeX\miktex\bin\x64"),
            r"C:\Program Files\MiKTeX\miktex\bin\x64"
        ]
        exe_name = "pdflatex.exe"

    for path in common_paths:
        full_path = os.path.join(path, exe_name)
        if os.path.exists(full_path):
            print(f"Found pdflatex at {full_path}")
            return full_path

    print("Error: 'pdflatex' not found. Please install a LaTeX distribution (e.g., TeX Live, MiKTeX).")
    return None

def generate_figures():
    """Run the figure generation script."""
    print("Generating figures...")
    try:
        # Run from project root
        result = subprocess.run([sys.executable, "lab/generate_figures.py"], check=True, capture_output=True, text=True)
        print(result.stdout)
        
        # Run the bounce figure generator for Paper 8
        print("Generating bounce experiment figures...")
        result_bounce = subprocess.run([sys.executable, "lab/generate_bounce_figure.py"], check=True, capture_output=True, text=True)
        print(result_bounce.stdout)
        
        # Run the stability analysis for Paper 8
        print("Running stability analysis...")
        result_stability = subprocess.run([sys.executable, "lab/analysis_stability.py"], check=True, capture_output=True, text=True)
        print(result_stability.stdout)

        # Run the Dilaton derivation for the Addendum
        print("Running Dilaton derivation...")
        result_dilaton = subprocess.run([sys.executable, "lab/theory/uv_completion_dilaton.py"], check=True, capture_output=True, text=True)
        print(result_dilaton.stdout)
        
    except subprocess.CalledProcessError as e:
        print("Error generating figures:")
        print(e.stderr)
        sys.exit(1)

def compile_paper(paper_path, pdflatex_cmd):
    """Compile a single LaTeX paper."""
    # paper_path is now e.g. 'papers/source/paper_01.tex'
    paper_filename = os.path.basename(paper_path)

    # Working directory for compilation should be 'papers/' so that 'figures/' paths resolve
    # We will copy the source file to 'papers/' temporarily, compile, then move PDF to 'papers/build/'
    # and delete the temporary tex file.

    papers_root = "papers"
    source_dir = "papers/source"
    build_dir = "papers/build"

    temp_tex_path = os.path.join(papers_root, paper_filename)

    print(f"Preparing to compile {paper_filename}...")

    try:
        # Copy .tex to papers/
        shutil.copy2(paper_path, temp_tex_path)

        # Run pdflatex inside the papers directory
        for i in range(2):
            print(f"  Pass {i+1}...")
            result = subprocess.run(
                [pdflatex_cmd, "-interaction=nonstopmode", paper_filename],
                cwd=papers_root,
                check=False,
                capture_output=True,
                text=True
            )
            if result.returncode != 0:
                print(f"LaTeX Error in Pass {i+1} for {paper_filename}:")
                print(result.stdout)
                print(result.stderr)
                # Continue to attempt moving the PDF even if there were errors

        # Move PDF to build directory
        pdf_filename = paper_filename.replace(".tex", ".pdf")
        src_pdf = os.path.join(papers_root, pdf_filename)
        dst_pdf = os.path.join(build_dir, pdf_filename)

        if os.path.exists(src_pdf):
            if os.path.exists(dst_pdf):
                os.remove(dst_pdf)
            shutil.move(src_pdf, dst_pdf)
            print(f"Successfully compiled and moved to {dst_pdf}")
        else:
            print(f"Error: PDF not found at {src_pdf}")
            return False

        return True

    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return False
    finally:
        # Cleanup temp .tex file
        if os.path.exists(temp_tex_path):
            os.remove(temp_tex_path)

def cleanup(papers_dir):
    """Remove auxiliary files generated by pdflatex in the papers root."""
    print("Cleaning up auxiliary files...")
    extensions = [".aux", ".log", ".out", ".pdf"]
    # Cleanup in 'papers/' since that's where we compiled
    for filename in os.listdir(papers_dir):
        if any(filename.endswith(ext) for ext in extensions):
            try:
                os.remove(os.path.join(papers_dir, filename))
                # print(f"Removed {filename}") # Reduce verbosity
            except OSError as e:
                print(f"Error removing {filename}: {e}")

def main():
    # Ensure we are in the project root
    if not os.path.exists("lab/generate_figures.py"):
        print("Error: Please run this script from the project root directory.")
        sys.exit(1)

    # 1. Generate Figures
    generate_figures()

    # 2. Find pdflatex
    pdflatex_cmd = find_pdflatex()
    if not pdflatex_cmd:
        print("Skipping PDF compilation.")
        return

    # 3. Compile Papers
    source_dir = "papers/source"
    if not os.path.exists(source_dir):
        print(f"Error: {source_dir} directory not found.")
        sys.exit(1)

    # Ensure build dir exists
    if not os.path.exists("papers/build"):
        os.makedirs("papers/build")

    for filename in os.listdir(source_dir):
        if filename.endswith(".tex"):
            compile_paper(os.path.join(source_dir, filename), pdflatex_cmd)

    # 4. Cleanup in 'papers/'
    cleanup("papers")

if __name__ == "__main__":
    main()
