import os
import subprocess
import sys
import shutil

def check_pdflatex():
    """Check if pdflatex is available in the system path."""
    if shutil.which("pdflatex") is None:
        # Check common Windows install locations
        common_paths = [
            os.path.expanduser(r"~\AppData\Local\Programs\MiKTeX\miktex\bin\x64"),
            r"C:\Program Files\MiKTeX\miktex\bin\x64"
        ]
        
        for path in common_paths:
            if os.path.exists(os.path.join(path, "pdflatex.exe")):
                print(f"Found pdflatex at {path}. Adding to PATH.")
                os.environ["PATH"] += os.pathsep + path
                return True
                
        print("Error: 'pdflatex' not found. Please install a LaTeX distribution (e.g., TeX Live, MiKTeX).")
        return False
    return True

def generate_figures():
    """Run the figure generation script."""
    print("Generating figures...")
    try:
        # Run from project root
        result = subprocess.run([sys.executable, "lab/generate_figures.py"], check=True, capture_output=True, text=True)
        print(result.stdout)
        
        # Run the bounce figure generator for Paper 8
        print("Generating bounce experiment figures...")
        result_bounce = subprocess.run([sys.executable, "lab/generate_bounce_figure.py"], check=True, capture_output=True, text=True)
        print(result_bounce.stdout)
        
        # Run the stability analysis for Paper 8
        print("Running stability analysis...")
        result_stability = subprocess.run([sys.executable, "lab/analysis_stability.py"], check=True, capture_output=True, text=True)
        print(result_stability.stdout)
        
    except subprocess.CalledProcessError as e:
        print("Error generating figures:")
        print(e.stderr)
        sys.exit(1)

def compile_paper(paper_path):
    """Compile a single LaTeX paper."""
    paper_dir = os.path.dirname(paper_path)
    paper_file = os.path.basename(paper_path)
    
    print(f"Compiling {paper_file}...")
    
    try:
        # Run pdflatex inside the papers directory
        # -interaction=nonstopmode prevents hanging on errors
        # Run twice to resolve references
        for i in range(2):
            print(f"  Pass {i+1}...")
            result = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", paper_file], 
                cwd=paper_dir, 
                check=False, # Changed to False to capture output on error
                capture_output=True,
                text=True # Capture as text
            )
            if result.returncode != 0:
                print(f"LaTeX Error in Pass {i+1} for {paper_file}:")
                print(result.stdout)
                print(result.stderr)
                return False # Indicate failure
        print(f"Successfully compiled {paper_file}")
        return True
    except Exception as e:
        print(f"An unexpected error occurred during compilation: {e}")
        return False

def cleanup(papers_dir):
    """Remove auxiliary files generated by pdflatex."""
    print("Cleaning up auxiliary files...")
    extensions = [".aux", ".log", ".out"]
    for filename in os.listdir(papers_dir):
        if any(filename.endswith(ext) for ext in extensions):
            try:
                os.remove(os.path.join(papers_dir, filename))
                print(f"Removed {filename}")
            except OSError as e:
                print(f"Error removing {filename}: {e}")

def main():
    # Ensure we are in the project root
    if not os.path.exists("lab/generate_figures.py"):
        print("Error: Please run this script from the project root directory.")
        sys.exit(1)

    # 1. Generate Figures
    generate_figures()

    # 2. Check for LaTeX
    if not check_pdflatex():
        print("Skipping PDF compilation.")
        return

    # 3. Compile Papers
    papers_dir = "papers"
    if not os.path.exists(papers_dir):
        print(f"Error: {papers_dir} directory not found.")
        sys.exit(1)

    for filename in os.listdir(papers_dir):
        if filename.endswith(".tex"):
            compile_paper(os.path.join(papers_dir, filename))

    # 4. Cleanup
    cleanup(papers_dir)

if __name__ == "__main__":
    main()
